version: "3.9"
services:
  fuelscraper: 
    build:
      context: .
      dockerfile: Dockerfile
    image: python
    restart: always
    volumes:
      - ./priceScraper.db:/usr/src/app/priceScraper.db
